[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[[redirects]]
  from = "https://sekaicouk-forget-me-not.netlify.app/"
  to = "https://you.sekai.co.uk"
  status = 301
  force = true