[build]
  publish = "__sapper__/export"
  command = "npm run export"

[[redirects]]
  from = "https://sekaicouk-forget-me-not.netlify.app/"
  to = "https://you.sekai.co.uk"
  status = 301
  force = true